### PR TITLE
fix: ensures the email is always treated as lowercase

### LINKED ISSUE #11: Uniformize mail addresses
The front end should ensure the email is lowercasing the email when login / registering an user

eg: Denis.gilet@xxx.com should match with denis.gillet@xxx.com

related to [graasp#62](https://github.com/graasp/graasp/issues/62)

### PR DESCRIPTION
**Pull request by Julien-Torrent**
close #11

### CODE REVIEW

File: src/components/SignUp.js [hunk 1]
```diff
@@ -102,7 +102,7 @@ class SignUp extends Component {
 
   handleRegister = async () => {
     const { email, name } = this.state;
-    const checkingEmail = emailValidator(email);
+    const checkingEmail = emailValidator(email.toLowerCase());
```
Comment (pyphilia) [inline src/components/SignUp.js:105]: Perhaps add a new variable `lowercaseEmail = email.toLowercase()` and use it in the next lines.

**Review by pyphilia — CHANGES_REQUESTED** [review]

**Review by pyphilia — APPROVED** [review]
