### PR TITLE
fix: enable TS strict mode

### LINKED ISSUE #460: [CHORE] Activate `strict` mode in TS config

### PR DESCRIPTION
**Pull request by spaenleh**
In this PR:
- enable TS strict mode

For this a few changes had to be made. Please let me know if you think some of them should be changed.

close #460

### CODE REVIEW

File: src/hooks/mobile.tsx [hunk 1]
```diff
@@ -12,8 +12,14 @@ const enum MobileSearchParams {
...
+    return {
+      isMobile: true as const,
+      challenge,
+    };
+  }
   return {
-    isMobile: challenge !== undefined && challenge !== null,
+    isMobile: false as const,
     challenge,
   };
```
Comment (spaenleh) [inline src/hooks/mobile.tsx:24]: Here I changed the code so the return type is a discriminated union that allows the challenge to be linked to the value of the `isMobile` boolean for type narrowing.

File: tsconfig.json [hunk 2]
```diff
@@ -1,10 +1,10 @@
 {
   "compilerOptions": {
-    "target": "es2016",
+    "target": "esnext",
     "module": "esnext",
     "esModuleInterop": true,
     "forceConsistentCasingInFileNames": true,
-    "strict": false,
+    "strict": true,
```
Comment (spaenleh) [inline tsconfig.json:7]: Enable strict mode

File: src/context/RecaptchaContext.tsx [hunk 3]
```diff
@@ -36,16 +36,18 @@ export const RecaptchaProvider = ({ children, siteKey }: Props) => {
...
             const token = await window.grecaptcha.execute(siteKey, { action });
             resolve(token);
           } catch (err) {
-            // if we are in dev and the error is that tge client id is not set, we resolve to a mock value
+            // if we are in dev and the error is that the client id is not set, we resolve to a mock value
             if (
-              err.toString().includes('Invalid reCAPTCHA client id') &&
+              err instanceof Error &&
+              (err.toString().includes('Invalid reCAPTCHA client id') ||
+                err.toString().includes('No reCAPTCHA clients exist')) &&
```
Comment (spaenleh) [inline src/context/RecaptchaContext.tsx:50]: I added the second error matching as I got it during development and testing when no key was used.

File: package.json [hunk 4]
```diff
@@ -17,7 +17,7 @@
     "@graasp/sdk": "4.29.1",
     "@graasp/stylis-plugin-rtl": "2.2.0",
     "@graasp/translations": "1.37.1",
-    "@graasp/ui": "5.0.1",
+    "@graasp/ui": "5.2.1",
```
Comment (spaenleh) [inline package.json:20]: In this update from UI, the ThemeProvider accepts `ReactNode` as children which is ok with supplying `null`. Before this was not possible.

File: cypress/tsconfig.json [hunk 5]
```diff
@@ -1,4 +1,5 @@
 {
+  "extends": "../tsconfig.json",
```
Comment (spaenleh) [inline cypress/tsconfig.json:2]: No idea why this was missing

File: cypress/support/server.ts [hunk 6]
```diff
@@ -38,57 +36,6 @@ export const mockGetCurrentMember = (
...
-        });
-      }
-
-      return reply({
-        body: allMembers,
-        statusCode: StatusCodes.OK,
-      });
-    },
-  ).as('getMembers');
-};
```
Comment (spaenleh) [inline cypress/support/server.ts:90]: These mocks were unused so I removed them.

File: src/Root.tsx [hunk 7]
```diff
@@ -25,7 +25,7 @@ const Content = () => {
       i18n={i18n}
       langs={langs}
       languageSelectSx={{ mb: 2, mr: 2 }}
-      languageSelectLabel={null}
+      languageSelectLabel=""
```
Comment (ReidyT) [inline src/Root.tsx:28]: It is possible to provide nothing? Otherwise, it's okay like that

```suggestion
```

File: src/context/RecaptchaContext.tsx (hunk 3 above)
Comment (ReidyT) [inline src/context/RecaptchaContext.tsx:50]: Should we use const here?

File: src/hooks/mobile.tsx [hunk 8]
```diff
@@ -12,8 +12,14 @@ const enum MobileSearchParams {
 export const useMobileAppLogin = () => {
   const [searchParams] = useSearchParams();
   const challenge = searchParams.get(MobileSearchParams.CHALLENGE);
+  if (challenge !== undefined && challenge !== null) {
```
Comment (ReidyT) [inline src/hooks/mobile.tsx:15]: I think you could simplify?

```suggestion
  if (challenge) {
```

**Review by ReidyT — APPROVED** [review]
LGTM ⛩️

**Review by pyphilia — APPROVED** [review]
LGTM 🦛

File: src/Root.tsx (hunk 7 above)
Comment (spaenleh) [reply src/Root.tsx:28]: It would be possible but currently, if nothing is provided, a default value is used and it is not translated.

File: src/context/RecaptchaContext.tsx (hunk 3 above)
Comment (spaenleh) [reply src/context/RecaptchaContext.tsx:50]: Mhmm are we supposed to re-use them ? I think having them hardcoded here reduces the number of indirections.

File: src/hooks/mobile.tsx (hunk 8 above)
Comment (spaenleh) [reply src/hooks/mobile.tsx:15]: Hmmm ... Not sure, it would also check that is is not an empty string ... Maybe ?

File: src/context/RecaptchaContext.tsx (hunk 3 above)
Comment (ReidyT) [reply src/context/RecaptchaContext.tsx:50]: it's okay for me
